#!/usr/bin/env sh
# ------------------------------------------------------------
# Gradle start up script for UN*X
# Generated by Gradle 8.7
# ------------------------------------------------------------

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
        exit 1
    fi
else
    JAVACMD="java"
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = false ] && [ "$darwin" = false ] ; then
    MAX_FD="maximum"
    if [ "$MAX_FD" != "maximum" ] ; then MAX_FD="maximum"; fi
    ulimit -n 2048 > /dev/null 2>&1
fi

CLASSPATH=$(dirname "$0")/gradle/wrapper/gradle-wrapper.jar

# For Cygwin and MSYS, convert paths.
if $cygwin || $msys ; then
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")
fi

exec "$JAVACMD" \
  "-Xmx64m" \
  "-Xms64m" \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain "$@"
